-- UNIVUE core database
-- Safe public access is exposed through read policies and SECURITY DEFINER RPCs.

create extension if not exists pgcrypto;

create table public.products (
  code text primary key,
  name text not null,
  category text not null check (category in ('FORMAL', 'T_SHIRT', 'PE_UNIFORM')),
  gender text check (gender in ('MALE', 'FEMALE') or gender is null),
  price numeric(10, 2) not null check (price >= 0),
  image_path text not null,
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.kiosks (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  display_name text not null,
  location text not null default '',
  active boolean not null default true,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.staff_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'STAFF' check (role in ('STAFF', 'ADMIN')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.inventory (
  product_code text not null references public.products(code) on update cascade on delete restrict,
  size text not null check (size in ('XS', 'S', 'M', 'L', 'XL', 'XXL')),
  quantity integer not null default 0 check (quantity between 0 and 30),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key (product_code, size)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  kiosk_id uuid references public.kiosks(id) on delete set null,
  customer_name text not null,
  student_id text not null,
  college_department text not null,
  contact_number text not null,
  fulfillment text not null check (fulfillment in ('PICKUP', 'CAMPUS_DELIVERY')),
  notes text not null default '',
  payment_method text not null check (payment_method in ('CASH', 'GCASH')),
  subtotal numeric(10, 2) not null default 0 check (subtotal >= 0),
  total numeric(10, 2) not null default 0 check (total >= 0),
  status text not null default 'AWAITING_PAYMENT' check (status in ('AWAITING_PAYMENT', 'PAID', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_code text not null references public.products(code) on update cascade on delete restrict,
  size text not null check (size in ('XS', 'S', 'M', 'L', 'XL', 'XXL')),
  quantity integer not null check (quantity between 1 and 30),
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  line_total numeric(10, 2) generated always as (quantity * unit_price) stored
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  method text not null check (method in ('CASH', 'GCASH')),
  amount numeric(10, 2) not null check (amount >= 0),
  status text not null default 'PENDING' check (status in ('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED')),
  provider_reference text,
  confirmed_at timestamptz,
  confirmed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.receipts (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  receipt_number text not null unique,
  printed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.assistance_requests (
  id uuid primary key default gen_random_uuid(),
  access_token uuid not null default gen_random_uuid(),
  kiosk_id uuid references public.kiosks(id) on delete set null,
  product_code text references public.products(code) on update cascade on delete set null,
  size text check (size in ('XS', 'S', 'M', 'L', 'XL', 'XXL') or size is null),
  order_reference text,
  message text not null default 'Student requested staff assistance.',
  status text not null default 'PENDING' check (status in ('PENDING', 'ACKNOWLEDGED', 'RESOLVED', 'CANCELLED')),
  requested_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  resolved_at timestamptz,
  handled_by uuid references auth.users(id) on delete set null
);

create table public.inquiry_logs (
  id bigint generated by default as identity primary key,
  kiosk_id uuid references public.kiosks(id) on delete set null,
  product_code text references public.products(code) on update cascade on delete set null,
  size text check (size in ('XS', 'S', 'M', 'L', 'XL', 'XXL') or size is null),
  available_quantity integer check (available_quantity between 0 and 30),
  stock_status text check (stock_status in ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK') or stock_status is null),
  success boolean not null default true,
  response_ms integer check (response_ms >= 0),
  queried_at timestamptz not null default now()
);

create index orders_created_at_idx on public.orders (created_at desc);
create index orders_status_idx on public.orders (status, created_at desc);
create index assistance_requests_status_idx on public.assistance_requests (status, requested_at desc);
create index inquiry_logs_queried_at_idx on public.inquiry_logs (queried_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();
create trigger kiosks_set_updated_at before update on public.kiosks
for each row execute function public.set_updated_at();
create trigger staff_profiles_set_updated_at before update on public.staff_profiles
for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();
create trigger payments_set_updated_at before update on public.payments
for each row execute function public.set_updated_at();

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1 from public.staff_profiles
    where user_id = auth.uid() and active
  );
$$;

create or replace function public.inventory_overview(p_product_code text)
returns table (size text, quantity integer, status text)
language sql
stable
security definer
set search_path = public
as $$
  select i.size,
         i.quantity,
         case when i.quantity = 0 then 'OUT_OF_STOCK'
              when i.quantity <= 3 then 'LOW_STOCK'
              else 'AVAILABLE' end as status
  from public.inventory i
  join public.products p on p.code = i.product_code and p.active
  where i.product_code = p_product_code
  order by array_position(array['XS','S','M','L','XL','XXL'], i.size);
$$;

create or replace function public.check_inventory(p_product_code text, p_size text)
returns table (product_code text, size text, quantity integer, status text)
language sql
stable
security definer
set search_path = public
as $$
  select i.product_code,
         i.size,
         i.quantity,
         case when i.quantity = 0 then 'OUT_OF_STOCK'
              when i.quantity <= 3 then 'LOW_STOCK'
              else 'AVAILABLE' end as status
  from public.inventory i
  join public.products p on p.code = i.product_code and p.active
  where i.product_code = p_product_code and i.size = upper(p_size)
  limit 1;
$$;

create or replace function public.record_inquiry(
  p_kiosk_code text,
  p_product_code text,
  p_size text,
  p_response_ms integer default null
)
returns table (product_code text, size text, quantity integer, status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kiosk_id uuid;
  v_quantity integer;
  v_status text;
begin
  select id into v_kiosk_id from public.kiosks where code = p_kiosk_code and active;
  select c.quantity, c.status into v_quantity, v_status
  from public.check_inventory(p_product_code, p_size) c;

  insert into public.inquiry_logs(kiosk_id, product_code, size, available_quantity, stock_status, success, response_ms)
  values (v_kiosk_id, p_product_code, upper(p_size), v_quantity, v_status, v_quantity is not null, p_response_ms);

  return query select p_product_code, upper(p_size), v_quantity, v_status;
end;
$$;

create or replace function public.place_order(
  p_kiosk_code text,
  p_customer jsonb,
  p_items jsonb,
  p_fulfillment text,
  p_payment_method text,
  p_notes text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kiosk_id uuid;
  v_order_id uuid;
  v_reference text;
  v_item jsonb;
  v_product public.products%rowtype;
  v_code text;
  v_size text;
  v_quantity integer;
  v_total numeric(10, 2) := 0;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 20 then
    raise exception 'INVALID_ITEMS';
  end if;
  if p_fulfillment not in ('PICKUP', 'CAMPUS_DELIVERY') then raise exception 'INVALID_FULFILLMENT'; end if;
  if p_payment_method not in ('CASH', 'GCASH') then raise exception 'INVALID_PAYMENT_METHOD'; end if;
  if nullif(trim(p_customer->>'customerName'), '') is null
    or nullif(trim(p_customer->>'studentId'), '') is null
    or nullif(trim(p_customer->>'collegeDepartment'), '') is null
    or nullif(trim(p_customer->>'contactNumber'), '') is null then
    raise exception 'MISSING_CUSTOMER_DETAILS';
  end if;

  select id into v_kiosk_id from public.kiosks where code = p_kiosk_code and active;
  if v_kiosk_id is null then raise exception 'UNKNOWN_KIOSK'; end if;

  v_reference := 'UNIVUE-' || to_char(clock_timestamp(), 'YYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));
  insert into public.orders(reference, kiosk_id, customer_name, student_id, college_department, contact_number, fulfillment, notes, payment_method)
  values (
    v_reference, v_kiosk_id,
    left(trim(p_customer->>'customerName'), 120),
    left(trim(p_customer->>'studentId'), 60),
    left(trim(p_customer->>'collegeDepartment'), 120),
    left(trim(p_customer->>'contactNumber'), 40),
    p_fulfillment,
    left(coalesce(p_notes, ''), 500),
    p_payment_method
  ) returning id into v_order_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_code := v_item->>'item';
    v_size := upper(v_item->>'size');
    begin
      v_quantity := (v_item->>'quantity')::integer;
    exception when others then
      raise exception 'INVALID_QUANTITY';
    end;
    if v_quantity < 1 or v_quantity > 30 or v_size not in ('XS','S','M','L','XL','XXL') then
      raise exception 'INVALID_ORDER_ITEM';
    end if;

    select * into v_product from public.products where code = v_code and active;
    if not found then raise exception 'UNKNOWN_PRODUCT:%', v_code; end if;

    update public.inventory
    set quantity = quantity - v_quantity, updated_at = now()
    where product_code = v_code and size = v_size and quantity >= v_quantity;
    if not found then raise exception 'INSUFFICIENT_STOCK:%:%', v_code, v_size; end if;

    insert into public.order_items(order_id, product_code, size, quantity, unit_price)
    values (v_order_id, v_code, v_size, v_quantity, v_product.price);
    v_total := v_total + (v_product.price * v_quantity);
  end loop;

  update public.orders set subtotal = v_total, total = v_total where id = v_order_id;
  insert into public.payments(order_id, method, amount) values (v_order_id, p_payment_method, v_total);

  return jsonb_build_object(
    'id', v_order_id,
    'reference', v_reference,
    'total', v_total,
    'status', 'AWAITING_PAYMENT',
    'paymentStatus', 'PENDING'
  );
end;
$$;

create or replace function public.request_assistance(
  p_kiosk_code text,
  p_product_code text default null,
  p_size text default null,
  p_order_reference text default null,
  p_message text default 'Student requested staff assistance.'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kiosk_id uuid;
  v_request public.assistance_requests%rowtype;
begin
  select id into v_kiosk_id from public.kiosks where code = p_kiosk_code and active;
  if v_kiosk_id is null then raise exception 'UNKNOWN_KIOSK'; end if;
  if p_size is not null and upper(p_size) not in ('XS','S','M','L','XL','XXL') then raise exception 'UNKNOWN_SIZE'; end if;

  insert into public.assistance_requests(kiosk_id, product_code, size, order_reference, message)
  values (v_kiosk_id, p_product_code, upper(p_size), p_order_reference, left(coalesce(p_message, 'Student requested staff assistance.'), 300))
  returning * into v_request;

  return jsonb_build_object(
    'id', v_request.id,
    'accessToken', v_request.access_token,
    'status', v_request.status,
    'requestedAt', v_request.requested_at
  );
end;
$$;

create or replace function public.assistance_status(p_request_id uuid, p_access_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id', id,
    'status', status,
    'requestedAt', requested_at,
    'acknowledgedAt', acknowledged_at,
    'resolvedAt', resolved_at
  )
  from public.assistance_requests
  where id = p_request_id and access_token = p_access_token;
$$;

alter table public.products enable row level security;
alter table public.kiosks enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.receipts enable row level security;
alter table public.assistance_requests enable row level security;
alter table public.inquiry_logs enable row level security;

create policy products_public_read on public.products for select to anon, authenticated using (active or public.is_staff());
create policy kiosks_public_read on public.kiosks for select to anon, authenticated using (active or public.is_staff());
create policy inventory_public_read on public.inventory for select to anon, authenticated using (true);
create policy staff_profiles_self_read on public.staff_profiles for select to authenticated using (user_id = auth.uid() or public.is_staff());
create policy products_staff_all on public.products for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy kiosks_staff_all on public.kiosks for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy staff_profiles_staff_all on public.staff_profiles for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy inventory_staff_all on public.inventory for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy orders_staff_read on public.orders for select to authenticated using (public.is_staff());
create policy orders_staff_update on public.orders for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy order_items_staff_read on public.order_items for select to authenticated using (public.is_staff());
create policy payments_staff_read on public.payments for select to authenticated using (public.is_staff());
create policy payments_staff_update on public.payments for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy receipts_staff_all on public.receipts for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy assistance_staff_read on public.assistance_requests for select to authenticated using (public.is_staff());
create policy assistance_staff_update on public.assistance_requests for update to authenticated using (public.is_staff()) with check (public.is_staff());
create policy inquiry_logs_staff_read on public.inquiry_logs for select to authenticated using (public.is_staff());

revoke all on all tables in schema public from anon, authenticated;
grant select on public.products, public.inventory, public.kiosks to anon, authenticated;
grant select on public.staff_profiles to authenticated;
grant select, update on public.orders, public.payments, public.assistance_requests to authenticated;
grant select on public.order_items, public.inquiry_logs to authenticated;
grant select, insert, update on public.receipts to authenticated;
grant insert, update, delete on public.products, public.inventory, public.kiosks, public.staff_profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.inventory_overview(text) from public;
revoke all on function public.check_inventory(text, text) from public;
revoke all on function public.record_inquiry(text, text, text, integer) from public;
revoke all on function public.place_order(text, jsonb, jsonb, text, text, text) from public;
revoke all on function public.request_assistance(text, text, text, text, text) from public;
revoke all on function public.assistance_status(uuid, uuid) from public;
grant execute on function public.inventory_overview(text) to anon, authenticated;
grant execute on function public.check_inventory(text, text) to anon, authenticated;
grant execute on function public.record_inquiry(text, text, text, integer) to anon, authenticated;
grant execute on function public.place_order(text, jsonb, jsonb, text, text, text) to anon, authenticated;
grant execute on function public.request_assistance(text, text, text, text, text) to anon, authenticated;
grant execute on function public.assistance_status(uuid, uuid) to anon, authenticated;

insert into public.products(code, name, category, gender, price, image_path, description) values
  ('MALE_POLO', 'Male Polo', 'FORMAL', 'MALE', 450, '/images/products/male-polo.png', 'Official male school polo.'),
  ('FEMALE_BLOUSE', 'Female Blouse', 'FORMAL', 'FEMALE', 450, '/images/products/female-blouse.png', 'Official female school blouse.'),
  ('MALE_PANTS', 'Male Pants', 'FORMAL', 'MALE', 500, '/images/products/male-pants.png', 'Official male school pants.'),
  ('FEMALE_SKIRT', 'Female Skirt', 'FORMAL', 'FEMALE', 480, '/images/products/female-skirt.png', 'Official female school skirt.'),
  ('T_SHIRT', 'School T-Shirt (Unisex)', 'T_SHIRT', null, 250, '/images/products/school-t-shirt.jpg', 'Official unisex school T-shirt.'),
  ('PE_UNIFORM', 'PE Uniform (Unisex)', 'PE_UNIFORM', null, 550, '/images/products/pe-uniform.png', 'Official unisex PE uniform.');

insert into public.inventory(product_code, size, quantity)
select p.code, s.size, 10
from public.products p
cross join (values ('XS'), ('S'), ('M'), ('L'), ('XL'), ('XXL')) as s(size);

insert into public.kiosks(code, display_name, location)
values ('UNIVUE-01', 'UNIVUE Main Kiosk', 'NU Baliwag merchandise area');

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'assistance_requests'
  ) then alter publication supabase_realtime add table public.assistance_requests; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then alter publication supabase_realtime add table public.orders; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'payments'
  ) then alter publication supabase_realtime add table public.payments; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'inventory'
  ) then alter publication supabase_realtime add table public.inventory; end if;
end $$;
